In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import joblib

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/shivang98/Social-Network-ads-Boost/refs/heads/master/Social_Network_Ads.csv')
df.head(5)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [4]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [5]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df[['Gender', 'Age', 'EstimatedSalary']], df['Purchased'], test_size=0.2, random_state=42)
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)

In [7]:
accuracy_score(y_test, y_pred)*100

88.75

In [8]:
joblib.dump(lr_model, '../../Projects/models/logistic_regression_model.joblib')

['../../Projects/models/logistic_regression_model.joblib']

In [9]:
loaded_model = joblib.load('../../Projects/models/logistic_regression_model.joblib')

In [10]:
new_data = [[1,51,23000]]
new_data = pd.DataFrame(new_data, columns=['Gender','Age', 'EstimatedSalary'])
prediction = loaded_model.predict(new_data)
print("Prediction from loaded model:", prediction)

Prediction from loaded model: [1]